### ISSUE TITLE
Remove fblualib dependancy

### ISSUE THREAD

**Issue by albanD** [albanD/lunatic-python#3]
The goal here would be to remove the fblualib dependancy that is very heavy and complex to install. For that we could use direclly use the TH C API (and move back the lunatic python code to pure C code)

For the fblualib dependency, all the corresponding source and headers are in the `fblualib-*` folders. What we use from this source is:
- `PyObjectHandle` from `Utils.h`. This is just a wrapper over `PyObject`s this can be removed with some extra `Py_INCREF` calls.
- `LuaToPythonConverter` class from `LuaToPython.h`. In practice, the only thing used in this class is the `convertTensor` function used to create a numpy array from a Torch tensor.
- `NumpyArrayAllocator` and the corresponding `thpp` calls made in the `pushTensor` function in `pythoninlua.cpp`. This is the function creating a Torch tensor from a numpy array.

**Comment by hughperkins** [comment]
Yeah, I dabbled a bit with installing lunatic-python, but I found installing fblualib _very_ heavy, and sort of gave up.

By the way, I reckon you might consider changing the name.  For a few reasons:
- quite hard to pronounce
- sounds a bit strange
- doesnt really tell you what it does

In other news, as you know, I have a library that does something similar at https://github.com/hughperkins/pytorch  I cannot claim to have done 'due diligence' trying to install lunatic-python, but I did spend a couple of days kind of dabbling in it.  Anyway, it's ok to have competing projects, but might be nice to fold them together somehow someday.  If nothing else, it's more fun to work on projects with other people :-)

**Comment by albanD** [comment]
Hi,
Good news: this issue is now solved (the old version has been moved to another branch): a simple `python setup.py install` will install everything (assuming your torch install folder is `~/torch/install`) ! :)
I have no particular opinion on the name lunatic-python but since the changes I made are minor I will keep the original name sorry :/

I indeed saw pytorch and it looks quite nice, my opinion on the two projects:
- I think the two projects have very different goals: pytorch tries to replace (reduce when not possible to remove) the lua part that is around the core of torch (what I understood from what I read, maybe I am wrong and please correct me). This project is actually just a generic lua/python binding with specific care for tensor for performance reasons. This leads to a big difference: the lua part associated to any new feature added to Torch must be reimplemented in pytorch for it to be available. In lunatic python, it will be available with the rest of the lua API.
- I think if you look at a python script using both projects, it would look almost the same, even though the execution stack will be completely different: python/cython/(lua/)c in one case python/c/lua/c in the other case.
- I am not a python guy initially and I don't know cython that well. I have to admit I have more fun playing with the C api from python/lua/numpy/torch than writing an extensive number of line of cython.

**Comment by hughperkins** [comment]
> This leads to a big difference: the lua part associated to any new feature added to Torch must be reimplemented in pytorch for it to be available. In lunatic python, it will be available with the rest of the lua API.

pytorch can import any lua class, call methods on it and so on.  only the tensors are cythonized.

I have no objection to two competing projects. torch does need a python layer :-)  I dont have a strong opinion of whether the tensors should be cythonized, it was just how I did it at the start.  accessing the tensors via lua is ok too, and easier to maintain.

PS but I really do think you should reconsider the name of your project.  As an example, my DeepCL was originally called ClConvolve.  Within 1 week of changing the name, I got 4000 page views...

**Comment by albanD** [comment]
> pytorch can import any lua class, call methods on it and so on. only the tensors are cythonized.

I missed this point! nice!

**Comment by hughperkins** [comment]
Thanks! :-)
